#!/bin/sh

case "$1" in
	start)
		for i in $(ls /etc/init.d/S*); do
			if test -x "$i"; then
				logger -s "$($i start)"
			fi
		done
		;;

	stop)
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			# don't allow inetd, stunnel or httpd to be stopped, or webUI will stop working
			if test "$nm" = "rcinetd" -o "$nm" = "rcstunnel" -o "$nm" = "rchttp"; then continue; fi
			if $nm status >& /dev/null; then
				logger -s "$($nm stop)"
			fi
		done
		;;

	restart)
		lst=""
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			if $nm status >& /dev/null; then
				lst="$nm $lst"
				logger -s "$($nm stop)"
			fi
		done
		sleep 3
		for i in $lst; do
			logger -s "$($i start)"
		done
		;;

	status)
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			logger -s "$($nm status)"
		done
		;;
		
	init)
		for i in /etc/init.d/S??*; do
			f=$(basename $i)
			if grep -q 'sinit()' $i; then
				logger -s "$(rc${f#S??} init)"
			fi
		done
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status|init}" >&2
		exit 1
		;;
esac
