#!/bin/sh

# can this go away? /etc/modules replaces it?

DESC="Load kernel modules"
NAME=modload

CONF_MISC=/etc/misc.conf
CONF_MOD=/etc/modules

mod="MODLOAD_IPV6 MODLOAD_CRYPTODEV MODLOAD_CESA"

. $CONF_MISC

umask 077

# convert from /etc/misc.conf to /etc/modules for compatibility
sinit() {
if grep -q '^MODLOAD_' $CONF_MISC; then
	for i in $mod; do
		if grep -q "^$i=y" $CONF_MISC; then
			case $i in
				MODLOAD_IPV6) j=ipv6 ;;
				MODLOAD_CRYPTODEV) j=cryptodev ;;
				MODLOAD_CESA) j=marvell_cesa ;;
			esac
			sed -i "/^$j/d" $CONF_MOD
			echo $j >> $CONF_MOD
		fi

		if grep -q $i $CONF_MISC; then
			sed -i "/$i/d" $CONF_MISC
		fi
	done
fi
}

. /etc/init.d/common

mod=$(sed 's/#.*//' $CONF_MOD 2> /dev/null | tr -s '\n' ' ')
if test -z "${mod// }"; then
	echo "$NAME: no modules file or no modules to load."
	return 1
fi

case "$1" in
	start)
		echo -n "Starting $NAME: "
		modprobe -ab $mod
		omsg $?
		;;
	stop)
		# removing modules is not a good ideia... 
		echo -n "Stopping $NAME: "
		modprobe -r $mod
		omsg $?
		;;
	status)
		echo -n "$NAME: modules "
		st=0
		for i in $mod; do
			if ! lsmod | grep -q $i; then
				echo -n "$i NOT loaded, "
				st=1;
			fi
		done
		omsg $st
		;;
	restart) rcmodload start ;;
	*)  usage $0 "start|stop|status|init" ;;
esac
