#!/bin/sh

DESC="Manages LVM (Logical Volume Management)"
NAME=lvm
REQUIRE="device_mapper"
TYPE=sys

SERRORL=/var/log/systemerror.log

umask 077

. /etc/init.d/common

case "$1" in
	start)
		#require $NAME $REQUIRE
		modprobe -qa dm_mirror dm_snapshot

		echo -n "Starting $NAME: "
		sed -i '/No LVM support found for partition/d' $SERRORL 2>/dev/null
		vgscan --mknodes >& /dev/null
		vgchange -a y
		omsg $?
		;;

	stop)
		echo -n "Stopping $NAME: "

		for i in $(awk '/^\/dev\/dm-.*/{print $1}' /proc/mounts); do
			(cd /dev && CALLER=rclvm-stop ACTION=remove DEVTYPE=partition PWD=/dev MDEV=$(basename $i) /usr/sbin/hot.sh)
			if cryptsetup status $i >& /dev/null; then
				cryptsetup luksClose $(cat /sys/block/$(basename $i)/dm/name)
			fi
		done
		
		vgchange -a n >& /dev/null
		st=$?
# 		if test $st = 0; then
# 			stoprequired $NAME $REQUIRE
 			modprobe -qr dm_snapshot dm_mirror 
# 		fi
		omsg $st
		;;

	status)
		if dmsetup ls | grep -q "No devices found"; then
			rcdevice_mapper stop >& /dev/null
			echo $NAME stopped
			return 1
		else
			echo $NAME running
		fi
		;;

	restart) restart $NAME ;;

	*)  usage $0 "start|stop|status|restart" ;;
esac
