#!/bin/sh

DESC="Setup cryptographic volumes for dm-crypt/LUKS"
NAME=cryptsetup
REQUIRE="device_mapper"
TYPE=sys

CONF_MOD=/etc/modules
CONF_MISC=/etc/misc.conf
SERRORL=/var/log/systemerror.log

umask 077

. /etc/init.d/common

. $CONF_MISC

iload() {
	require $NAME $REQUIRE
	st=0
	if ! lsmod | grep -q dm_crypt; then
		modprobe -q dm-crypt
		st=$?
		if grep -q ^marvell_cesa $CONF_MOD; then
			modprobe -q marvell_cesa
		fi
	fi
}

iunload() {
	# removing modules recursively is unreliable, dont!
	# Also, dm_mod might be removed, even if in use by lvm
	mod="cbc ecb xts sha1_generic marvell_cesa dm_crypt"
	for j in $(seq 1 3); do
		lsm=$(lsmod)
		for i in $mod; do
			if test "$(echo "$lsm" | awk '/^'$i'/{print $3}')" = 0; then
				rmmod $i
				mod=$(echo $mod | sed -n 's/'$i'//p')
			fi
		done
	done
	stoprequired $NAME $REQUIRE 
}

case "$1" in
	start)
		st=0
		echo -n "Starting $NAME: "
		sed -i '/No cryptsetup support found for partition/d' $SERRORL 2>/dev/null
		#iload
		if test "$st" = 0 -a -f "$CRYPT_KEYFILE"; then
			for i in /dev/md[0-9]* /dev/dm-[0-9]* /dev/sd[a-z][1-9]*; do
				if ! test -e $i; then continue; fi
				dev=$(basename $i)
				if test -z "$(ls -A $(find /sys/block/ -type d -name holders | grep $dev))"; then
					if cryptsetup isLuks $i; then
						(cd /dev && CALLER=rccryptsetup-start ACTION=add DEVTYPE=partition PWD=/dev MDEV=$dev /usr/sbin/hot.sh)
					fi
				fi
			done
		fi
		omsg $st
		;;

	stop)
		echo -n "Stopping $NAME: "
		st=0

		for i in /dev/mapper/*-crypt; do
			if ! readlink -f $i >& /dev/null; then continue; fi
			j=$(basename $i)
			dm=$(basename $(realpath $i))
			h=$(ls -A /sys/block/$dm/slaves)
			if cryptsetup isLuks /dev/$h; then
				(cd /dev && CALLER=rccryptsetup-stop ACTION=remove DEVTYPE=partition PWD=/dev MDEV=$dm /usr/sbin/hot.sh)
				cryptsetup luksClose $j
 				st=$((st+$?))
			fi
		done

		if test $st != 0; then
			omsg $st
			return 1
		fi

		modprobe -qr cbc ecb xts sha1_generic dm_crypt marvell_cesa
		omsg 0
		return 0
		;;

	status)
		dmout=$(dmsetup ls --target crypt)
		if test -z "$dmout" -o "$dmout" = "No devices found"; then
			modprobe -r dm_crypt >& /dev/null
			rcdevice_mapper stop >& /dev/null
			echo $NAME stopped
			return 1
		else
			echo $NAME running
		fi
		;;

	restart) restart $NAME ;;

	load) iload ;;

	unload) iunload ;;

	*)  usage $0 "start|stop|status|restart|load|unload" ;;
esac
