#!/bin/sh

DESC="Secure Administrative HTTPS server"
NAME=stunnel
TYPE=net

INETD_CONF=/etc/inetd.conf
STUNNEL_PEM=/etc/ssl/certs/stunnel.pem
BOX_PEM=/etc/ssl/certs/server.pem

sinit() {
	if ! test -e $STUNNEL_PEM; then
		ln -sf $BOX_PEM $STUNNEL_PEM
	fi
}

. /etc/init.d/common

if check_inetd https || check_inetd swats; then
	exit 2
fi

case "$1" in
	start)
		avahi add https
		avahi add swats
		start $NAME
		;;
	stop)
		avahi remove https
		avahi remove swats
		stop $NAME
		;;
	status)	status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload|init" ;;
esac
